### This notebook explores the basics of NLP by implementing Bag of Words, N-gram and TF-IDF approach, how they differ from each other

In [ ]:
### Libraries Used

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import nltk
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [2]:
corpus = ["The weather is good today!!!", 
          "what does it mean to vectorize?", 
          "document classification is cool"]

In [3]:
#Initialize vectorizer:
vectorizer = CountVectorizer()

In [4]:
X = vectorizer.fit_transform(corpus)

In [5]:
X.toarray() # 1.

array([[0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [6]:
vectorizer.get_feature_names()

['classification',
 'cool',
 'document',
 'does',
 'good',
 'is',
 'it',
 'mean',
 'the',
 'to',
 'today',
 'vectorize',
 'weather',
 'what']

## N gram Approach

#### There is no concept of order or sequencein Vectorization technique shown above .Ordering things differently can create the meaning of sentences dramatically For instance

In [7]:
S1 = ["Los Angeles Lakers defeated Warriors", "Warriors defeated Los Angeles Lakers "]

In [8]:
Output=vectorizer.fit_transform(S1)

In [9]:
Output.toarray()

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

 These sentences are saying pretty different things But according to our model they are the same, there lies the problem

In [10]:
vector_ngram = CountVectorizer(ngram_range=(2,2))

In [11]:
X=vector_ngram.fit_transform(S1)

In [12]:
X.toarray()

array([[1, 0, 1, 1, 1, 0],
       [1, 1, 0, 0, 1, 1]], dtype=int64)

In [13]:
vector_ngram.get_feature_names()

['angeles lakers',
 'defeated los',
 'defeated warriors',
 'lakers defeated',
 'los angeles',
 'warriors defeated']

### With N gram we see that the word vector is now different and context is accounted

Now let see TF-IDF, so far we have assumed all words are equally importnat in a document , but that is not necessarily true  for example, words such as "The", "and"..etc although may appear a lot a in a document but do not tell us about the context of the sentence. To identify what weightage should be given to each word in a sentence, so that we can identify important words that is where we use TF-IDF


### TF-IDF

In [14]:
tfvectorizer=TfidfVectorizer(ngram_range=(2, 3))

In [15]:
X=tfvectorizer.fit_transform(S1)

In [16]:
X.toarray()

array([[0.30287281, 0.42567716, 0.        , 0.        , 0.42567716,
        0.42567716, 0.42567716, 0.30287281, 0.30287281, 0.        ,
        0.        ],
       [0.30287281, 0.        , 0.42567716, 0.42567716, 0.        ,
        0.        , 0.        , 0.30287281, 0.30287281, 0.42567716,
        0.42567716]])

In [17]:
tfvectorizer.get_feature_names()

['angeles lakers',
 'angeles lakers defeated',
 'defeated los',
 'defeated los angeles',
 'defeated warriors',
 'lakers defeated',
 'lakers defeated warriors',
 'los angeles',
 'los angeles lakers',
 'warriors defeated',
 'warriors defeated los']